name: Submodule Update Check

on:
  push:
    paths:
      - ".gitmodules"
      - "src/content/aeps/**"
  pull_request:
    paths:
      - ".gitmodules"
      - "src/content/aeps/**"
  schedule:
    - cron: "0 */6 * * *" # Check every 6 hours

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Submodule Update
        run: |
          git submodule update --remote --recursive
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected in submodules"
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add .
            git commit -m "chore: update submodules"
            git push
          else
            echo "No changes in submodules"
          fi

      - name: Trigger Build
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: submodule-update
